### ISSUE TITLE
Setting up one view model and permission handling

### ISSUE THREAD

**Issue by lokaimoma** [rafsanjani/blizzard#12]
Currently the way data is loaded into the views are quiet similar.
Is it a good idea to set up one view model to deal with populating 
data into the views

And for the location permission, the permission is asked right after 
the app is installed, i don't know if it is ideal to do it that way,
if no, then how best and when should the permission be 
asked for.

**Comment by rafsanjani** [comment]
Yes, you can use a single ViewModel for that purpose. You can make your Activity the owner of the ViewModel so that only a single instance of it will be loaded in memory.

**Comment by lokaimoma** [comment]
Ok thanks, i will try that then
