### ISSUE TITLE
Restore app state

### ISSUE THREAD

**Issue by rafsanjani** [rafsanjani/blizzard#37]
Fragments do not restore their state when user navigates, e, a navigation such as home ->favorites->home will completely restart the whole app flow and load weather for current city instead of retaining weather info for whatever city was searched.

<img src="https://user-images.githubusercontent.com/9197459/90990578-835f3300-e59a-11ea-876e-bc39d2f1c565.gif" width=250 height=500>

**Comment by lokaimoma** [comment]
No problem, on it 🤝
