### ISSUE TITLE
Incorrect notification data

### ISSUE THREAD

**Issue by rafsanjani** [rafsanjani/blizzard#41]
This information showed in the notification is incorrect

<img src="https://user-images.githubusercontent.com/9197459/91039614-c5bd5a00-e604-11ea-9818-d2e0961dd7b5.png" width=250 height=500>

**Comment by lokaimoma** [comment]
On it👍

**Comment by lokaimoma** [comment]
I think i fixed this in a previous PR, it's now okay, just that if there are multiply notifications the new one replaces the old one

**Comment by rafsanjani** [comment]
yeah looks good to me.
