### ISSUE TITLE
Time from  api not accurate.

### ISSUE THREAD

**Issue by lokaimoma** [rafsanjani/blizzard#8]
The time from the api isn't accurate and doesn't update when  a query made earlier is been made again. Any ideas on how to solve this.
![Screenshot_20200805-121956](https://user-images.githubusercontent.com/46226886/89407799-547e3b80-d717-11ea-9ad1-9c1c80ea15c4.jpg) Togo is one hour behind Morocco, but the time shown is wrong.

**Comment by rafsanjani** [comment]
I only get timezone information from the API and not actual time. Can you show me which endpoint gives you the time information?

**Comment by lokaimoma** [comment]
> I only get timezone information from the API and not actual time. Can you show me which endpoint gives you the time information?
![dt](https://user-images.githubusercontent.com/46226886/89413288-7def9500-d720-11ea-9ebd-aca068ff47bd.png)
This part of the data returned has the time in UNIX, UTC. With java.util.Date i multiply the value for the dt 1000L to get the date and the time.

**Comment by rafsanjani** [comment]
I've updated my comment. I've forgotten your slack handle, can you drop me a message there.

**Comment by lokaimoma** [comment]
> So a quick research from https://www.epochconverter.com/timezones has showed me that the timezone information returned is in fact the amount of hours to offset based on GMT. To get the accurate time of a city, we will first have to check what time it is in GMT and add the amount of seconds as showed in `timezone`
> 
> This is a sample response from Togo
> 
> ```
> {
>     "coord": {
>         "lon": 1.17,
>         "lat": 8
>     },
>     "weather": [
>         {
>             "id": 800,
>             "main": "Clear",
>             "description": "clear sky",
>             "icon": "01d"
>         }
>     ],
>     "base": "stations",
>     "main": {
>         "temp": 304.02,
>         "feels_like": 304.72,
>         "temp_min": 304.02,
>         "temp_max": 304.02,
>         "pressure": 1014,
>         "humidity": 46,
>         "sea_level": 1014,
>         "grnd_level": 990
>     },
>     "visibility": 10000,
>     "wind": {
>         "speed": 2.93,
>         "deg": 260
>     },
>     "clouds": {
>         "all": 0
>     },
>     "dt": 1596630711,
>     "sys": {
>         "country": "TG",
>         "sunrise": 1596606481,
>         "sunset": 1596651272
>     },
>     "timezone": 0,
>     "id": 2363686,
>     "name": "Togo",
>     "cod": 200
> }
> ```
> 
> Since it has a timezone offset of 0, we can return the current time in GMT and it should be accurate.
> 
> Alternatively, this is a response from London, UK
> 
> ```
> {
>     "coord": {
>         "lon": -0.13,
>         "lat": 51.51
>     },
>     "weather": [
>         {
>             "id": 802,
>             "main": "Clouds",
>             "description": "scattered clouds",
>             "icon": "03d"
>         }
>     ],
>     "base": "stations",
>     "main": {
>         "temp": 298.02,
>         "feels_like": 292.39,
>         "temp_min": 295.93,
>         "temp_max": 300.37,
>         "pressure": 1012,
>         "humidity": 33
>     },
>     "visibility": 10000,
>     "wind": {
>         "speed": 7.2,
>         "deg": 240
>     },
>     "clouds": {
>         "all": 40
>     },
>     "dt": 1596630929,
>     "sys": {
>         "type": 1,
>         "id": 1414,
>         "country": "GB",
>         "sunrise": 1596601852,
>         "sunset": 1596656524
>     },
>     "timezone": 3600,
>     "id": 2643743,
>     "name": "London",
>     "cod": 200
> }
> ```
> 
> London is in GMT+1 at this time of the year so the returned response in `timezone` is `3600`. This is the amount of seconds we need to add to the global GMT time to get an accurate time in London hence GMT+1, which is essentially GMT + 1hour or GMT + 3600seconds

oh great then i will use that one then, thanks much🤝
